# Generated by Django 4.2 on 2023-05-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Population",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "population",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Mid Year Population"
                    ),
                ),
                (
                    "ds_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ds_population",
                        to="pu.dsdivision",
                        verbose_name="DS Division",
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-ds_division"),
                "unique_together": {("ds_division", "year")},
            },
        ),
    ]
