# Generated by Django 4.2 on 2023-05-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DSDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="DS Division")),
            ],
        ),
        migrations.CreateModel(
            name="MOHDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "has_multiple_ds",
                    models.BooleanField(
                        blank=True, verbose_name="has multiple DS divisions"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BHA", "BHA"),
                            ("BHB", "BHB"),
                            ("BHC", "BHC"),
                            ("DHA", "DHA"),
                            ("DHB", "DHB"),
                            ("DHC", "DHC"),
                            ("PMCU", "PMCU"),
                            ("MOH", "MOH"),
                            ("UNIT", "UNIT"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "ds_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pu.dsdivision",
                        verbose_name="DS division",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="dsdivision",
            name="moh_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pu.mohdivision",
                verbose_name="MOH division",
            ),
        ),
    ]
